//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Associate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_Status
    {
        public int DrId { get; set; }
        public string Dr_Names { get; set; }
        public string Status { get; set; }
        public Nullable<int> Contact { get; set; }
    }
}
