//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Associate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inpateint
    {
        public int WardId { get; set; }
        public string Ward_No { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<System.DateTime> DOA { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public string Status { get; set; }
        public string Remedy_Treatment { get; set; }
        public string Note { get; set; }
        public Nullable<int> Service_Number { get; set; }
    }
}
