//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Associate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicalAssociatesEntities : DbContext
    {
        public medicalAssociatesEntities()
            : base("name=medicalAssociatesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consumable> Consumables { get; set; }
        public virtual DbSet<DoctorsStatu> DoctorsStatus { get; set; }
        public virtual DbSet<Lab_Test_Requests> Lab_Test_Requests { get; set; }
        public virtual DbSet<Lab_Tests> Lab_Tests { get; set; }
        public virtual DbSet<Patient_Cue> Patient_Cue { get; set; }
        public virtual DbSet<Patient_List> Patient_List { get; set; }
        public virtual DbSet<Prescription_List> Prescription_List { get; set; }
        public virtual DbSet<X_Rays> X_Rays { get; set; }
    }
}
