//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Associate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Cue
    {
        public int Service_Number { get; set; }
        public int PatientID { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> DrId { get; set; }
        public string Presiding_Dr { get; set; }
        public string Admission { get; set; }
    }
}
